# Generated by Django 5.2.8 on 2025-12-10 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medtrackerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_notes', to='medtrackerapp.medication')),
            ],
        ),
    ]
